const DEFAULT_IGNORES = [
  'node_modules',
  'dist',
  '.project',
  '.happier',
  '.happier-stack',
  'coverage',
  '/output',
  '.reviews',
  '.agent-contexts',
  '.dev',
  '.clawpatch',
  '.playwright-mcp',
  '.antigravitycli',
  'evidence',
  'graphify-out',
  '/workspace',
  '.expo',
  'target',
  'Pods',
  '.next',
  '.runner-snapshots',
  'package-dist',
  '.restore.*',
  '.dist.hstack-*',
  'apps/ui/ios/build',
  'apps/ui/android/app/build',
  'apps/ui/android/build',
  'apps/ui/android/.gradle',
  'apps/cli/tools/unpacked',
  'apps/cli/*:*',
  'subagents/dev-plugin-projection-runtime-closure',
  '.env.local',
  'env.local',
  '*.log',
  '*.trace',
  '.DS_Store',
];

function yamlString(value) {
  return JSON.stringify(String(value));
}

function sessionName(targetName) {
  return `happier-${String(targetName).replace(/[^a-z0-9_-]+/gi, '-')}`;
}

export function renderMutagenProject({ sourceDir, targets }) {
  const lines = [
    '# Generated by hstack. User configuration lives in dev-targets.json.',
    'sync:',
    '  defaults:',
    '    mode: "one-way-replica"',
    '    flushOnCreate: true',
    '    ignore:',
    '      vcs: true',
    '      paths:',
    ...DEFAULT_IGNORES.map((entry) => `        - ${yamlString(entry)}`),
  ];
  for (const target of targets) {
    lines.push(
      `  ${sessionName(target.name)}:`,
      `    alpha: ${yamlString(sourceDir)}`,
      `    beta: ${yamlString(`${target.ssh}:${target.repoDir}`)}`,
    );
  }
  return `${lines.join('\n')}\n`;
}

export function buildMutagenProjectArgs(action, projectFile) {
  const normalized = String(action ?? '').trim();
  const supported = new Set(['start', 'list', 'flush', 'pause', 'resume', 'reset', 'terminate']);
  if (!supported.has(normalized)) {
    throw new Error(`[dev-targets] unsupported Mutagen project action: ${normalized}`);
  }
  return [
    'project',
    normalized,
    ...(normalized === 'start' ? ['--no-global-configuration'] : []),
    '--project-file',
    String(projectFile),
  ];
}
